apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rpa-mit-events
  description: The MIT events
  annotations:
    github.com/project-slug: defra/est-mit-events
    dev.azure.com/project: DEFRA-MIT
    dev.azure.com/build-definition: rpa-mit-events
    sonarqube.org/project-key: rpa-mit-events
    grafana/dashboard-selector: "folderTitle == 'Managed Prometheus'"
    backstage.io/kubernetes-id: rpa-mit-events
  links:
    - url: https://github.com/DEFRA/est-mit-events
      title: View repository
      icon: github
    - url: https://sonarcloud.io/summary/overall?id=rpa-mit-events
      title: SonarCloud Analysis
    - url: https://snyk.io/test/github/DEFRA/rpa-mit-events
      title: Snyk Analysis
  tags:
    - dotnet
    - back-end
    - storage-account
    - application-insights
spec:
  type: backend
  lifecycle: alpha
  owner: "group:default/lap-mit"
  system: "system:default/lap-mit-system"
  dependsOn:
    - "resource:default/rpa-mit-event-storage-queue"
    - "resource:default/rpa-mit-event-storage-table"
    - "resource:default/ADPINFAI01"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rpa-mit-event-storage-table
  description: Event storage table
  tags:
    - storage-account
    - table
spec:
  type: table-storage
  owner: "group:default/lap-mit"
  system: "system:default/lap-mit-system"
  dependsOn: 
    - "resource:default/adpinfst01"