# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local trpaing

services:
  rpa-mit-events:
    image: rpa-mit-events-development
    container_name: rpa-mit-events-development
    ports:
      - "3001:80"
    volumes:
      - ./rpaMITEventsFunction:/home/dotnet/rpa.MIT.Events.Function
      - ./rpaMITEventsFunction.Trpa:/home/dotnet/rpa.MIT.Events.Function.Trpa