services:
  rpa-mit-events:
    build:
      context: .
    image: rpa-mit-events
    container_name: rpa-mit-events
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      FUNCTIONS_WORKER_RUNTIME: dotnet-isolated
      AzureWebJobsSecretStorageType: ${AzureWebJobsSecretStorageType}
      AzureWebJobsStorage: ${AzureWebJobsStorage}
      TableConnectionString: ${TableConnectionString}      
      QueueConnectionString: ${QueueConnectionString}      
      EventTableName: ${EventTableName}
      EventQueueName: ${EventQueueName}