{{- include "ffc-helm-library.container-config-map" (list . "est-mit-events.config-map") -}}
{{- define "est-mit-events.config-map" -}}
data:
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  QueueConnectionString__queueServiceUri: {{ quote .Values.container.queueConnectionString__queueServiceUri }}
  QueueConnectionString__credential: {{ quote .Values.container.queueConnectionString__credential }}
  TableConnectionString__tableServiceUri: {{ quote .Values.container.tableConnectionString__tableServiceUri }}
  TableConnectionString__credential: {{ quote .Values.container.tableConnectionString__credential }}
  EventQueueName: {{ quote .Values.container.eventQueueName }}
  EventTableName: {{ quote .Values.container.eventTableName }}
{{- end -}}
